site_name: Delve Engine Architecture
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true